### ISSUE TITLE
[ Week 1 ] 1주차 워크북 미션

### ISSUE THREAD

**Issue by kayeon2** [DS-UMC-7th/UMC-7th-Yoni#1]
### 🛠 Mission

개발을 위한 프로젝트 세팅, MVC 패턴과 UIViewController, UIComponents 이해하기

### 📝 To-do

- [x] 프로젝트 파일 생성 및 개발 환경 세팅
- [x] 로그인 모델 구현
- [x] 로그인 레이아웃 구현

### 🔍 접근 방법

- AutoLayout 적용
- iPhone 15 Pro, iPhone 13 mini 시뮬레이터에서 테스트
