### ISSUE TITLE
[ Week 6 ] 6주차 워크북 미션

### ISSUE THREAD

**Issue by kayeon2** [DS-UMC-7th/UMC-7th-Yoni#11]
### 🛠 Mission

객체지향 프로그래밍(OOP)과 SOILD 원칙 이해하기

### 📝 To-do

- [x] 세부 화면 레이아웃 구현
- [ ] 구현한 화면 중 한 화면을 OOP가 적용되도록 리팩토링
- [ ] 구현한 화면 중 한 화면을 SOLID 원칙 중 하나가 적용되도록 리팩토링

### 🔍 접근 방법

- SnapKit
- UINavigationController
- UICollectionView
