### ISSUE TITLE
[ Week 7 ] 7주차 워크북 미션 

### ISSUE THREAD

**Issue by kayeon2** [DS-UMC-7th/UMC-7th-Yoni#13]
### 🛠 Mission

Network, Alamofire, URLSession, json 이해하기

### 📝 To-do

- [x] 카카오톡 API 애플리케이션 등록
- [x] 카카오톡 로그인 버튼에 카카오톡 API 연결
- [x] 로그인 성공 시 키체인에 토큰, 닉네임 저장
- [x] 로그인 후 화면 연결
- [x] 마이페이지 유저 이름을 키체인에 저장된 닉네임으로 변경

### 🔍 접근 방법

- Alamofire
- Keychain
