### ISSUE TITLE
[ Week 8 ] 8주차 워크북 미션 

### ISSUE THREAD

**Issue by kayeon2** [DS-UMC-7th/UMC-7th-Yoni#15]
### 🛠 Mission

Moya와 Multipart 통신 이해하기

### 📝 To-do

- [ ] 검색 화면 및 검색 세부 화면 레이아웃 구현
- [ ] 메인 화면과 검색 화면 간 화면 전환
- [ ] 검색 세부 화면에서 통신 및 데이터 바인딩

### 🔍 접근 방법

- Moya를 사용한 API 통신
