### ISSUE TITLE
[ Week 2 ] 2주차 워크북 미션

### ISSUE THREAD

**Issue by kayeon2** [DS-UMC-7th/UMC-7th-Yoni#2]
### 🛠 Mission

AutoLayout과 SnapKit 활용, 화면 전환과 UITabBarController 이해하기

### 📝 To-do

- [x] TabBarController로 메인 화면 구성
- [x] 로그인 버튼 클릭 시 메인 화면으로 전환
- [x] 마이페이지 레이아웃 구현
- [x] 프로필 수정 페이지 레이아웃 구현
- [x] 프로필 관리 버튼 클릭 시 프로필 수정 페이지로 전환

### 🔍 접근 방법

- SnapKit을 활용하여 오토 레이아웃 적용
- 로그인 페이지에서 모달 방식으로 화면 전환
- 마이페이지에서 네비게이션 방식으로 화면 전환
- UITabBarController로 메인 화면 구성
