### ISSUE TITLE
[ Week 4 ] 4주차 워크북 미션

### ISSUE THREAD

**Issue by kayeon2** [DS-UMC-7th/UMC-7th-Yoni#6]
### 🛠 Mission

UICollectionView와 UISegmentedControl 이해하기

### 📝 To-do

- [x] 메인 화면 레이아웃 구현
- [x] SegmentedControl 구현
- [x] 선택된 세그먼트 볼드 처리
- [ ] 선택된 세그먼트 밑줄 처리
- [x] '추천' 세그먼트 외  빈 화면 처리
- [x] CollectionView 구현

### 🔍 접근 방법

- UISegmentedControl
- UICollectionViewFlowLayout
