### ISSUE TITLE
[ Week 5 ] 5주차 워크북 미션

### ISSUE THREAD

**Issue by kayeon2** [DS-UMC-7th/UMC-7th-Yoni#8]
### 🛠 Mission

UIScrollView 이해하기

### 📝 To-do

- [x] 기존 Home 탭 ScrollView 구현
- [x] ScrollView 내부에 컴포넌트 추가
- [x] '발매 상품' 컬렉션 뷰 구현
- [x] '본격 한파대비! 연말 필수템 모음' 컬렉션 뷰 구현

### 🔍 접근 방법

- UIScrollView
- UICollectionView
- Then
